# Pytorch exercises

Exercise 1: Write a PyTorch code to create a tensor of size (3, 3) filled with random values between 0 and 1.

In [1]:
import torch

# Create a tensor of size (3, 3) with random values between 0 and 1
tensor1 = torch.rand((3, 3))
print(tensor1)

tensor([[0.1825, 0.2663, 0.7229],
        [0.8638, 0.4104, 0.2635],
        [0.4907, 0.6097, 0.9187]])


Exercise 2:
Create a tensor of size (5, 2) filled with zeros.

In [2]:
# Create a tensor of size (5, 2) filled with zeros
tensor2 = torch.zeros((5, 2))
print(tensor2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


Exercise 3:
Implement a PyTorch code to multiply two tensors of size (2, 3) and (3, 4) respectively.

In [3]:
# Create two tensors of size (2, 3) and (3, 4)
tensor3a = torch.rand((2, 3))
tensor3b = torch.rand((3, 4))

# Multiply the tensors
result3 = torch.matmul(tensor3a, tensor3b)
print(result3)

tensor([[0.8309, 0.7805, 0.8519, 0.9325],
        [0.5006, 0.5612, 0.6138, 0.6305]])


Exercise 4:
Create a PyTorch tensor with values ranging from 5 to 10.

In [4]:
# Create a tensor with values ranging from 5 to 10
tensor4 = torch.arange(5, 11)
print(tensor4)

tensor([ 5,  6,  7,  8,  9, 10])


Exercise 5:
Write a PyTorch code to compute the mean of a tensor.

In [5]:
# Create a tensor
tensor5 = torch.rand((3, 3))

# Compute the mean of the tensor
mean5 = tensor5.mean()
print(mean5)

tensor(0.4382)


Exercise 6:
Implement a PyTorch code to compute the element-wise product of two tensors of the same size.

In [6]:
# Create two tensors of the same size
tensor6a = torch.rand((3, 3))
tensor6b = torch.rand((3, 3))

# Compute the element-wise product
result6 = tensor6a * tensor6b
print(result6)

tensor([[0.6329, 0.0947, 0.4348],
        [0.1855, 0.8131, 0.7126],
        [0.0361, 0.1519, 0.4298]])


Exercise 7:
Create a PyTorch tensor with values sampled from a normal distribution with mean 0 and standard deviation 1.

In [7]:
# Create a tensor with values sampled from a normal distribution
tensor7 = torch.randn((3, 3))
print(tensor7)


tensor([[-0.7107, -0.3093,  0.1746],
        [ 1.9801,  0.5439,  0.7717],
        [-0.5176,  0.5169, -1.1159]])


Exercise 8:
Write a PyTorch code to find the maximum value in a tensor.

In [8]:
# Create a tensor
tensor8 = torch.rand((3, 3))

# Find the maximum value in the tensor
max8 = tensor8.max()
print(max8)


tensor(0.9342)


Exercise 9:
Implement a PyTorch code to compute the cross entropy loss between predicted values and target values.

In [9]:
import torch.nn as nn

# Create predicted and target tensors
predicted = torch.tensor([[0.2, 0.3, 0.5], [0.1, 0.6, 0.3]], requires_grad=True)
target = torch.tensor([2, 1])

# Compute the cross entropy loss
loss_fn = nn.CrossEntropyLoss()
loss9 = loss_fn(predicted, target)
print(loss9)


tensor(0.8966, grad_fn=<NllLossBackward0>)


Exercise 10: Create a PyTorch tensor and then convert it to a NumPy array.

In [10]:
# Create a tensor
tensor10 = torch.rand((3, 3))

# Convert it to a NumPy array
numpy_array10 = tensor10.numpy()
print(numpy_array10)


[[0.6565436  0.1349554  0.68663156]
 [0.6587776  0.884874   0.13497645]
 [0.5857414  0.7171008  0.9324497 ]]


Exercise 11:
Write a PyTorch code to perform a matrix transpose operation on a tensor.

In [11]:
# Create a tensor
tensor11 = torch.rand((3, 4))

# Perform a matrix transpose operation
transposed11 = tensor11.t()
print(transposed11)


tensor([[0.9800, 0.2377, 0.7749],
        [0.0522, 0.6521, 0.2156],
        [0.3806, 0.3458, 0.8748],
        [0.8255, 0.8126, 0.7158]])


Exercise 12:
Implement a PyTorch code to concatenate two tensors along a specified dimension.

In [12]:
# Create two tensors
tensor12a = torch.rand((2, 3))
tensor12b = torch.rand((2, 3))

# Concatenate the tensors along dimension 0
concatenated12 = torch.cat((tensor12a, tensor12b), dim=0)
print(concatenated12)


tensor([[0.2794, 0.9280, 0.3132],
        [0.8857, 0.1623, 0.7768],
        [0.3947, 0.4907, 0.9867],
        [0.7685, 0.4215, 0.0117]])


Exercise 13:
Create a PyTorch tensor and then convert it to a CUDA tensor if CUDA is available.

In [13]:
# Create a tensor
tensor13 = torch.rand((3, 3))

# Convert it to a CUDA tensor if CUDA is available
if torch.cuda.is_available():
    tensor13 = tensor13.to('cuda')
print(tensor13)


tensor([[0.7518, 0.0843, 0.3499],
        [0.8766, 0.8022, 0.2937],
        [0.9676, 0.8720, 0.7940]])


Exercise 14:
Write a PyTorch code to find the indices of non-zero elements in a tensor.

In [14]:
# Create a tensor
tensor14 = torch.tensor([[0, 1, 0], [2, 0, 3]])

# Find the indices of non-zero elements
non_zero_indices14 = torch.nonzero(tensor14)
print(non_zero_indices14)


tensor([[0, 1],
        [1, 0],
        [1, 2]])


Exercise 15:
Implement a PyTorch code to perform element-wise exponentiation on a tensor.

In [15]:
# Create a tensor
tensor15 = torch.rand((3, 3))

# Perform element-wise exponentiation
exponentiated15 = torch.exp(tensor15)
print(exponentiated15)


tensor([[2.2821, 1.0930, 1.4377],
        [1.5754, 2.5230, 1.8676],
        [1.7566, 2.5493, 1.9758]])


Exercise 16:
Create a PyTorch tensor and then reshape it into a tensor of different dimensions.

In [16]:
# Create a tensor
tensor16 = torch.rand((2, 6))

# Reshape it into a tensor of different dimensions
reshaped16 = tensor16.view((3, 4))
print(reshaped16)


tensor([[0.1987, 0.4849, 0.3197, 0.8512],
        [0.0644, 0.2549, 0.9454, 0.1683],
        [0.8043, 0.8217, 0.2788, 0.0564]])


Exercise 17:
Write a PyTorch code to compute the cosine similarity between two tensors.

In [17]:
import torch.nn.functional as F

# Create two tensors
tensor17a = torch.rand((3,))
tensor17b = torch.rand((3,))

# Compute the cosine similarity
cosine_similarity17 = F.cosine_similarity(tensor17a.unsqueeze(0), tensor17b.unsqueeze(0))
print(cosine_similarity17)


tensor([0.9936])


Exercise 18: Implement a PyTorch code to perform element-wise logarithm on a tensor.

In [18]:
# Create a tensor
tensor18 = torch.rand((3, 3))

# Perform element-wise logarithm
logarithm18 = torch.log(tensor18)
print(logarithm18)


tensor([[-1.4011, -0.6505, -0.0455],
        [-0.3269, -0.1327, -0.6186],
        [-0.0249, -1.6005, -1.0548]])


Exercise 19:
Create a PyTorch tensor and then calculate its standard deviation.

In [19]:
# Create a tensor
tensor19 = torch.rand((3, 3))

# Calculate its standard deviation
std19 = tensor19.std()
print(std19)


tensor(0.2873)


Exercice 20: Write a PyTorch code to compute the Frobenius norm of a tensor.

In [20]:
# Create a tensor
tensor20 = torch.rand((3, 3))

# Compute the Frobenius norm of the tensor
frobenius_norm20 = torch.norm(tensor20)
print(frobenius_norm20)


tensor(1.5816)
